{-# LANGUAGE OverloadedStrings #-}

module Main where

import Config (getConfig, configDbPath)
import Database.Persist.Sql (runSqlPool)
import Database.Persist.Sqlite (withSqlitePool)
import Control.Monad.Logger (runStderrLoggingT)
import Db (migrateAll)

main :: IO ()
main = do
    cfg <- getConfig

    -- runStderrLoggingT: provides a logging context (persistent needs somewhere to send SQL logs)
    -- withSqlitePool: opens a pool of SQLite connections to the DB file
    --   configDbPath cfg  = the file path (e.g. "urls.db")
    --   10                = max connections in the pool
    --   \pool -> ...      = callback that receives the pool to use

    runStderrLoggingT $ withSqlitePool (configDbPath cfg) 10 $ \pool -> do
    -- migrateAll: generated by Persistent from our schema in Db.hs
    -- runSqlPool: runs the migration using a connection from the pool
    -- effect: CREATE TABLE IF NOT EXISTS for all tables in the schema        
        runSqlPool migrateAll pool
